{% set version = "1.9.3" %}

package:
  name: pytorch-3dunet
  version: {{ version }}

source:
  url: https://github.com/wolny/pytorch-3dunet/archive/refs/tags/{{ version }}.tar.gz
  sha256: 42e4d7b7c03ec5be78d82a7d80e21b66e61f1333590e316fd762f909a70b5cec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - predict3dunet = pytorch3dunet.predict:main
    - train3dunet = pytorch3dunet.train:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - nomkl
    - tensorboard
    - tqdm
    - h5py
    - scipy
    - scikit-image
    - pyyaml
    - pip

test:
  imports:
    - pytorch3dunet
    - pytorch3dunet.unet3d
    - pytorch3dunet.augment
    - pytorch3dunet.datasets
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
    - pip check

about:
  home: https://github.com/wolny/pytorch-3dunet
  summary: 'Versatile U-Net implementation for volumetric semantic segmentation written in PyTorch'
  description: |
    PyTorch implementation of 3D U-Net and its variants (ResidualUNet3D, ResidualUNetSE3D).
    The code allows for training the U-Net for both: semantic segmentation (binary and multi-class) 
    and regression problems (e.g. de-noising, learning deconvolutions).
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/wolny/pytorch-3dunet
  dev_url: https://github.com/wolny/pytorch-3dunet

extra:
  recipe-maintainers:
    - wolny
